MODEL:
  NAME: 'resnet50'
  TYPE: 'backbone'
  NUM_CLASSES: 1000
  LOSS_FUN: 'soft_cross_entropy'
  LOAD_WEIGHTS_FROM_URL: True
OPTIM:
  OPTIMIZER: 'sgd'
  BASE_LR: 1.0
  LR_POLICY: 'steps'
  MAX_EPOCH: 20
  MOMENTUM: 0.9
  WEIGHT_DECAY: 2e-5
  WARMUP_EPOCHS: 0
  DAMPENING: 0.0
  NESTEROV: True
  EMA_UPDATE_PERIOD: 32
TRAIN:
  BATCH_SIZE: 1024
  LABEL_SMOOTHING: 0.1
  MIXUP_ALPHA: 0.0
  PCA_STD: 0.1
TEST:
  BATCH_SIZE: 400
SCALING:
  RES_MULT_A: 1.0
  WIDTH_MULT: 1.0
DATASET:
  PATH: "PATH/TO/YOUR/DATASET"
  NAME: 'imagenet'
NUM_GPUS: 4
